name: Delete Branch After Merge

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Delete merged PR branch
    # Only run if the PR was merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Gather PR branch info
        id: info
        run: |
          echo "head_ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "head_repo=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_OUTPUT
          echo "base_repo=${{ github.event.pull_request.base.repo.full_name }}" >> $GITHUB_OUTPUT
          if [ "${{ github.event.pull_request.head.repo.full_name }}" = "${{ github.event.pull_request.base.repo.full_name }}" ]; then
            echo "same_repo=true" >> $GITHUB_OUTPUT
          else
            echo "same_repo=false" >> $GITHUB_OUTPUT
          fi
      - name: Delete head branch
        if: steps.info.outputs.same_repo == 'true' && steps.info.outputs.head_ref != 'main'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const ref = `heads/${{ github.event.pull_request.head.ref }}`;
            core.info(`Attempting to delete ${ref} in ${owner}/${repo}`);
            try {
              await github.rest.git.deleteRef({ owner, repo, ref });
              core.info(`Deleted ${ref}`);
            } catch (error) {
              core.warning(`Could not delete ${ref}: ${error.message}`);
            }
